spring:

  pidfile: shared/tmp/pids/application.pid

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      enableSelfPreservation: false
      waitTimeInMsWhenSyncEmpty: 0
logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'

---
spring:
  profiles: eureka-peer1
  instance:
    hostname: 10.3.45.151
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.3.47.62:8761
---
spring:
  profiles: eureka-peer2
eureka:
  instance:
    hostname: 10.3.47.62
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://10.3.45.151:8761