spring:

  pidfile: shared/tmp/pids/application.pid

server:
  port: ${PORT:8761}


eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'

---
spring:
  profiles: eureka-peer1
server:
  port: ${PORT:8762}
eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer2:8761/eureka/
---
spring:
  profiles: eureka-peer2
server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: peer2

  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/
