spring:

  application:
    name: micro

  #boot:
  #  admin:
  #    context-path: /admin

  jackson:
    serialization:
      indent_output: true
endpoints:
    health:
      sensitive: false
server:
  port: ${PORT:8761}


zuul:
  routes:
    client:
      path: /client/**
      serviceId: client


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true

    healthcheck:
      enabled: true

logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'


