spring:

  pidfile: shared/tmp/pids/application.pid

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'

---
spring:
  profiles: peer1
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2/eureka/
---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1/eureka/