spring:

  pidfile: shared/tmp/pids/application.pid

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      enableSelfPreservation: false
      waitTimeInMsWhenSyncEmpty: 0
logging:
    level:
        org.springframework: 'OFF'
        com.xiaojiuwo.models.mapper: 'DEBUG'

---
spring:
  profiles: eureka-peer1
server:
  port: ${PORT:8762}
eureka:
  instance:
    hostname: peer1
    leaseRenewalIntervalInSeconds: 3
  client:
    prefer-same-zone-eureka: true
    use-dns-for-fetching-service-urls: false
    region: shawn
    availability-zones:
      shawn: 'peer1,peer2'
    serviceUrl:
      'peer1': 'http://peer1:8762/'
      'peer2': 'http://peer2:8761/'
---
spring:
  profiles: eureka-peer2
server:
  port: ${PORT:8761}
eureka:
  instance:
    hostname: peer2
    leaseRenewalIntervalInSeconds: 3

  client:

    prefer-same-zone-eureka: true
    use-dns-for-fetching-service-urls: false
    region: shawn
    availability-zones:
      shawn: 'peer1,peer2'
    serviceUrl:
      'peer1': 'http://peer1:8762/'
      'peer2': 'http://peer2:8761/'

